baseURL = "https://williamkarvar.link"
languageCode = "pt-br"
theme = "anubis2"
title = "William Gabriel Karvat"

[pagination]
pagerSize = 5

[params.author]
name = "William Gabriel Karvat"


[params]
paginationSinglePost = true

colorTheme = "dark"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "pt-br"
math = false # true: enable mathjax globally (default is false)
toc = true

social = [
    { id = "github", url = "https://github.com/WgkLink"},
    { id = "linkedin", url = "https://www.linkedin.com/in/william-gabriel-karvat-065480201/" }
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'base16-snazzy'
tabWidth           = 4